use case_study;
select * from nhan_vien;
select *from vi_tri; 
select * from trinh_do;
select * from bo_phan; 
select *from hop_dong;
select *from hop_dong_chi_tiet;
select *from dich_vu_di_kem;
select *from dich_vu;
select *from khach_hang;
select *from loai_khach;
select*from kieu_thue;
select * from loai_dich_vu;
